### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by S-Koell** [mickeypearce/oradew-vscode#9] opened 2018-07-31 13:31 UTC
When trying to Initialize Workspace/Version I am running into those Problems on my Windows 10 machine:

- When having a space in the folder path it wont work
- After fixing the path to have no spaces in it, I'm getting the following error:
```
> Executing task in folder Oradew_Test: c:\VSCode\data\extensions\mp.oradew-vscode-0.1.0\out\gulp.cmd --cwd \\wacker.corp\user\koellex001\Data\Oradew_Test --gulpfile c:\VSCode\data\extensions\mp.oradew-vscode-0.1.0\out\gulpfile.js --color true --silent true initProject <

Der Befehl "node" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
The terminal process terminated with exit code: 1
(translated: command "node" is wrong or could not be found)
```

- When trying to use "npm rebuild" it also doesnt find that command

I haven't worked with Linux systems before but it sounds like these errors are all because I'm running windows and these commands are not there by default.

**Comment by mickeypearce** [comment] 2018-08-01 06:37
Hey @S-Koell,

Node.js is not part of this extension and should be downloaded and installed seperatelly. And so it is also [Git](https://git-scm.com/). (I should write this prerequisites to readme file maybe... :smile: )

I advise you to get a [Node 9](https://nodejs.org/en/download/releases/) (latest version: [Node.js 9.11.2](https://nodejs.org/download/release/v9.11.2/)) as node-oracledb driver in extension is precompiled for this Node version. If you install node you also get "npm".

As for spaces in folder path, this is bug that I should fix. Good find!

**Comment by mickeypearce** [comment] 2018-08-04 10:27
Duplicate of #5

**Closed** 2018-08-07 07:51 UTC
Labels: bug, question
