### ISSUE TITLE
Select DB

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#17] opened 2019-02-27 21:13 UTC
Hi,
is possible to select the DB where to execute current script/procedure?

**Comment by mickeypearce** [comment] 2019-02-28 09:03
Hey @Danieleeee , It is possible.

1. Oradew chooses DB USER accordingly to directory structure where the file/script is saved.

For example, if you have this structure:

 * scripts
   * USER1
     * file_1.sql
   * USER2
     * files_2.sql
* src
  * USER1
    * PROCEDURE
      * p_procedure1.sql
  * USER2
    * PROCEDURE
      * p_procedure2.sql

When you compile `file1_sql` or `p_procedure1.sql` it compiles with user USER1 (you must have its credentials saved in `dbconfig.json`). And then USER2 when you compile `file_2.sql`, etc.


2. As for compiling to different DBs, you can choose between 3 different environments you can select with vscode command:

`Oradew: Compile Current File`  --- compiles to "DEV" environment (DEV is default env)
`Oradew: TEST: Compile Current File` --- compiles to "TEST" environment
`Oradew: UAT: Compile Current File` --- compiles to "UAT" environment

Environemnts credentials are also defined in `dbconfig.json`.

Hopefully I made it more clear.

**Comment by DanRic** [comment] 2019-02-28 09:47
I know that I can change user, but I need to change DB (SVIL,TEST,PROD, DEBUG,...)

**Comment by DanRic** [comment] 2019-02-28 09:58
It would be nice to be able to select a file and run it in a DB and Schema selected from a list.
Without having to create the folder structure each time

**Comment by mickeypearce** [comment] 2019-02-28 10:11
I could do sth like `Compile to Files with Choose connection` type of command that would open a dialog list with all user/env to choose from. 

For global dbconfig I could make a setting  `oradew.dbConfigFile` with default value `${workspaceFolder}/dbconfig.json`.

**Comment by DanRic** [comment] 2019-02-28 11:38
Yes, thanks!
you could use db connections list in Language PL/SQL extension.

**Comment by mickeypearce** [comment] 2019-03-04 19:34
I am adding a "set DB environment" command that let you select an environment which is then used as execution environment for all commands (compile, etc).

Environment selection list is generated from dbconfig, so you can also add you custom environments (debug, etc) and you are not limited only to predefined envs.

This new "set environment" command has also unselected option <None>. This means that every command prompts you with environment selection on command execution. This will be most suitable usage in your case maybe.

I also added a status item to indicate which environment is currently set.

I am not adding user selection at the moment , although possible , it would require quite a bit restructuring... But I think DB selection prompt could me more useful.

**Comment by mickeypearce** [comment] 2019-03-05 18:56
Released in v0.3.0.

**Comment by DanRic** [comment] 2019-03-06 08:40
Thank you!
I have noticed that problems are not shown for custom environments
![1](https://user-images.githubusercontent.com/43675808/53867287-cff42e80-3ff3-11e9-8fd6-a27434522e05.png)

**Comment by mickeypearce** [comment] 2019-03-06 10:04
What do you mean by problem are not shown? "ORA-00900: invalid SQL statemen" is your problem. Can you please provide more information, an example maybe compared to "DEV" enviroment for example.

**Comment by DanRic** [comment] 2019-03-06 10:10
If I Compile current file:
![1](https://user-images.githubusercontent.com/43675808/53873178-0e8fe600-4000-11e9-99bb-db088c855387.png)

I have no problems if it isn't in the src folder:
![2](https://user-images.githubusercontent.com/43675808/53873236-30896880-4000-11e9-94c1-3a179631b94f.png)

If I run the same command in the src folder I have errors and problems:
![2](https://user-images.githubusercontent.com/43675808/53873348-77775e00-4000-11e9-8e04-d075ff5776bf.png)

![1](https://user-images.githubusercontent.com/43675808/53873302-5b73bc80-4000-11e9-8636-a1107a8b729e.png)

**Comment by mickeypearce** [comment] 2019-03-06 10:14
Try setting a property in oradewrc.json configuration:
`"compile.force": true`

**Comment by DanRic** [comment] 2019-03-06 11:01
compile.force is true
This is what I see in the terminal (no errors):
![1](https://user-images.githubusercontent.com/43675808/53876636-87467080-4007-11e9-9230-a3b4f6ed60a0.png)

**Comment by mickeypearce** [comment] 2019-03-06 11:31
Your workspace is not git repostiroy (`git init` would solve that). 

Sql file compiled with "Success" though. It failed to stage file in git repo (git add) as it does when file is successfully compiled.

**Comment by DanRic** [comment] 2019-03-06 11:35
The file has errors, look KK_VARCHAR2(500).
Why it says: Sql file compiled with "Success"
And no problem is shown?

**Comment by mickeypearce** [comment] 2019-03-06 11:45
Is it saved maybe? 

please send me an actual file or repo so I could reproduce.

**Comment by mickeypearce** [comment] 2019-03-06 11:50
Aha I see file is actually outsitde of SRC directory.... I will look into it and let you know.

**Comment by mickeypearce** [comment] 2019-03-06 11:53
This is because file is not in dir structure ./src/OBJECT_TYPE/OBJECT_NAME.SQL. Information we need  to get errors for object after compilation (from table all_errors) is therefore missing in your case.

**Comment by DanRic** [comment] 2019-03-06 12:00
OK, thanks.
If I put it in the scr folder I have this error though I have set compile.force = true :
![1](https://user-images.githubusercontent.com/43675808/53879846-c7a9ec80-400f-11e9-80b3-9914d76fe983.png)

**Comment by mickeypearce** [comment] 2019-03-06 12:05
Compile again, but I am not sure why "compile.force": true wuold not work.

**Closed** 2019-03-07 12:57 UTC
Labels: enhancement
